root: /ec-cube/html/
admin_dir: admin/
tpl: /ec-cube/html/user_data/packages/default/
admin_tpl: /ec-cube/html/user_data/packages/admin/
image_path: /ec-cube/html/upload/save_image/
root_dir: /Applications/MAMP/htdocs/ec-cube
root_urlpath: /ec-cube/html
template_code: templatefashion
admin_route: admin
user_data_route: user_data
public_path: /html
public_path_realdir: /Applications/MAMP/htdocs/ec-cube/html
image_save_realdir: /Applications/MAMP/htdocs/ec-cube/html/upload/save_image
image_temp_realdir: /Applications/MAMP/htdocs/ec-cube/html/upload/temp_image
user_data_realdir: /Applications/MAMP/htdocs/ec-cube/html/user_data
block_default_realdir: /Applications/MAMP/htdocs/ec-cube/src/Eccube/Resource/template/default/Block
block_realdir: /Applications/MAMP/htdocs/ec-cube/app/template/templatefashion/Block
template_default_realdir: /Applications/MAMP/htdocs/ec-cube/src/Eccube/Resource/template/default
template_default_html_realdir: /Applications/MAMP/htdocs/ec-cube/html/template/default
template_admin_realdir: /Applications/MAMP/htdocs/ec-cube/src/Eccube/Resource/template/admin
template_admin_html_realdir: /Applications/MAMP/htdocs/ec-cube/html/template/admin
template_realdir: /Applications/MAMP/htdocs/ec-cube/app/template/templatefashion
template_html_realdir: /Applications/MAMP/htdocs/ec-cube/html/template/templatefashion
template_temp_realdir: /Applications/MAMP/htdocs/ec-cube/app/cache/eccube/template
csv_temp_realdir: /Applications/MAMP/htdocs/ec-cube/app/cache/eccube/csv
plugin_realdir: /Applications/MAMP/htdocs/ec-cube/app/Plugin
plugin_temp_realdir: /Applications/MAMP/htdocs/ec-cube/app/cache/plugin
plugin_html_realdir: /Applications/MAMP/htdocs/ec-cube/html/plugin
admin_urlpath: /ec-cube/html/template/admin
front_urlpath: /ec-cube/html/template/templatefashion
image_save_urlpath: /ec-cube/html/upload/save_image
image_temp_urlpath: /ec-cube/html/upload/temp_image
user_data_urlpath: /ec-cube/html/user_data
plugin_urlpath: /ec-cube/html/plugin
